### ISSUE TITLE
Bug in `Available Options` 

### ISSUE THREAD

**Issue by oimken** [anomalylabs/tags-field_type#8]
https://github.com/anomalylabs/tags-field_type/blob/master/src/TagsFieldTypeOptions.php#L19

Remove the `(array)`:
```php
$options = array_get($fieldType->getConfig(), 'options', []);
```

Fixed.

**Comment by RyanThompson** [comment]
Please always open issues up in Pyrocms/pyrocms repository. I will forget about these open here.

`[tags-field_type] Your title here`

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/tags-field_type/commit/8b1da7a268ea1988ab7a58ecfe9d1b7970f713d6
